services:
  # 1. The Database (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: ticketvelo-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: ticketvelo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # 2. Redis (For Caching & Locking)
  redis:
    image: redis:7-alpine
    container_name: ticketvelo-redis
    ports:
      - "6379:6379"

  # 3. Zookeeper & Kafka (For Async Messaging)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: ticketvelo-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: ticketvelo-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 4. Prometheus (The Database for Metrics)
  prometheus:
    image: prom/prometheus:latest
    container_name: ticketvelo-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Mount our config
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allow access to localhost app

  # 5. Grafana (The Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: ticketvelo-grafana
    ports:
      - "3001:3000" # We use port 3001 to avoid conflict
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

volumes:
  postgres_data: