spring:
  application:
    name: ticketvelo

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketvelo_db
    username: admin
    password: password123
    driver-class-name: org.postgresql.Driver

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect